using System.ComponentModel;

namespace tradelr.Library.geo
{
    public enum WorldRegions
    {
        [Description("Asia")]
        Asia,
        [Description("Middle East and North Africa")]
        MiddleEastNorthAfrica,
        [Description("European Union")]
        Europe,
        [Description("Europe non-EU")]
        EuropeNonEU,
        [Description("North America")]
        NorthAmerica,
        [Description("Central America")]
        CentralAmerica,
        [Description("South America")]
        SouthAmerica,
        [Description("Africa")]
        Africa,
        [Description("Australia and Oceania")]
        Oceania,
        [Description("Antartica")]
        Antartica
    }
    /*
    public static class CountryGroups
    {
        public static Dictionary<WorldRegions, List<Country>> Earth
            = new Dictionary<WorldRegions, List<Country>>()
                  {
                      {
                          WorldRegions.Asia, new List<Country>()
                                                 {
                                                     Country.Bangladesh,
                                                     WorldCountries.Bhutan,
                                                     WorldCountries.Brunei,
                                                     WorldCountries.Cambodia,
                                                     WorldCountries.China,
                                                     WorldCountries.HongKong,
                                                     WorldCountries.India,
                                                     WorldCountries.Indonesia,
                                                     WorldCountries.Japan,
                                                     WorldCountries.Kazakhstan,
                                                     WorldCountries.Kyrgyzstan,
                                                     WorldCountries.NorthKorea,
                                                     WorldCountries.SouthKorea,
                                                     WorldCountries.Laos,
                                                     WorldCountries.Macau,
                                                     WorldCountries.Malaysia,
                                                     WorldCountries.Maldives,
                                                     WorldCountries.Mongolia,
                                                     WorldCountries.Myanmar,
                                                     WorldCountries.Nepal,
                                                     WorldCountries.Philippines,
                                                     WorldCountries.Singapore,
                                                     WorldCountries.SriLanka,
                                                     WorldCountries.Taiwan,
                                                     WorldCountries.Tajikistan,
                                                     WorldCountries.Thailand,
                                                     WorldCountries.Turkmenistan,
                                                     WorldCountries.Uzbekistan,
                                                     WorldCountries.Vietnam,
                                                 }
                          },
                      {
                          WorldRegions.MiddleEastNorthAfrica, new List<WorldCountries>()
                                                                  {
                                                                      WorldCountries.Afghanistan,
                                                                      WorldCountries.Algeria,
                                                                      WorldCountries.Azerbaijan,
                                                                      WorldCountries.Bahrain,
                                                                      WorldCountries.Egypt,
                                                                      WorldCountries.Gibraltar,
                                                                      WorldCountries.Iran,
                                                                      WorldCountries.Iraq,
                                                                      WorldCountries.Israel,
                                                                      WorldCountries.Jordan,
                                                                      WorldCountries.Kuwait,
                                                                      WorldCountries.Lebanon,
                                                                      WorldCountries.Libya,
                                                                      WorldCountries.Morocco,
                                                                      WorldCountries.NagornoKarabakh,
                                                                      WorldCountries.NorthernCyprus,
                                                                      WorldCountries.Oman,
                                                                      WorldCountries.Pakistan,
                                                                      WorldCountries.PalestinianTerritories,
                                                                      WorldCountries.Qatar,
                                                                      WorldCountries.SaudiArabia,
                                                                      WorldCountries.Somalia,
                                                                      WorldCountries.Somaliland,
                                                                      WorldCountries.Syria,
                                                                      WorldCountries.Tunisia,
                                                                      WorldCountries.Turkey,
                                                                      WorldCountries.UAE,
                                                                      WorldCountries.Yemen
                                                                  }
                          },
                      {
                          WorldRegions.Europe, new List<WorldCountries>()
                                                   {
                                                       WorldCountries.Abkhazia,
                                                       WorldCountries.Aland,
                                                       WorldCountries.Albania,
                                                       WorldCountries.Andorra,
                                                       WorldCountries.Armenia,
                                                       WorldCountries.Austria,
                                                       WorldCountries.Belarus,
                                                       WorldCountries.Belgium,
                                                       WorldCountries.BosniaHerzegovina,
                                                       WorldCountries.Bulgaria,
                                                       WorldCountries.Croatia,
                                                       WorldCountries.Cyprus,
                                                       WorldCountries.CzechRepublic,
                                                       WorldCountries.Denmark,
                                                       WorldCountries.Estonia,
                                                       WorldCountries.Finland,
                                                       WorldCountries.France,
                                                       WorldCountries.Georgia,
                                                       WorldCountries.Germany,
                                                       WorldCountries.Greece,
                                                       WorldCountries.Guernsey,
                                                       WorldCountries.Hungary,
                                                       WorldCountries.Iceland,
                                                       WorldCountries.Ireland,
                                                       WorldCountries.IsleOfMan,
                                                       WorldCountries.Italy,
                                                       WorldCountries.Jersey,
                                                       WorldCountries.Kosovo,
                                                       WorldCountries.Latvia,
                                                       WorldCountries.Liechtenstein,
                                                       WorldCountries.Lithuania,
                                                       WorldCountries.Luxembourg,
                                                       WorldCountries.Macedonia,
                                                       WorldCountries.Malta,
                                                       WorldCountries.Moldova,
                                                       WorldCountries.Monaco,
                                                       WorldCountries.Montenegro,
                                                       WorldCountries.Netherlands,
                                                       WorldCountries.Norway,
                                                       WorldCountries.Poland,
                                                       WorldCountries.Portugal,
                                                       WorldCountries.Pridnestrovie,
                                                       WorldCountries.Reunion,
                                                       WorldCountries.Romania,
                                                       WorldCountries.Russia,
                                                       WorldCountries.SanMarino,
                                                       WorldCountries.Serbia,
                                                       WorldCountries.Slovakia,
                                                       WorldCountries.Slovenia,
                                                       WorldCountries.SouthOssetia,
                                                       WorldCountries.Spain,
                                                       WorldCountries.Svalbard,
                                                       WorldCountries.Sweden,
                                                       WorldCountries.Switzerland,
                                                       WorldCountries.Ukraine,
                                                       WorldCountries.UK,
                                                       WorldCountries.VaticanCity
                                                   }
                          },
                      {
                          WorldRegions.NorthAmerica, new List<WorldCountries>()
                                                         {
                                                             WorldCountries.Ascension,
                                                             WorldCountries.Canada,
                                                             WorldCountries.Greenland,
                                                             WorldCountries.Mexico,
                                                             WorldCountries.SaintPierreMiquelon,
                                                             WorldCountries.US
                                                         }
                          },
                      {
                          WorldRegions.CentralAmerica, new List<WorldCountries>()
                                                           {
                                                               WorldCountries.Anguilla,
                                                               WorldCountries.Antigua,
                                                               WorldCountries.Aruba,
                                                               WorldCountries.Bahamas,
                                                               WorldCountries.Barbados,
                                                               WorldCountries.Belize,
                                                               WorldCountries.Bermuda,
                                                               WorldCountries.BritishVirginIslands,
                                                               WorldCountries.CaymanIslands,
                                                               WorldCountries.ClippertonIsland,
                                                               WorldCountries.CostaRica,
                                                               WorldCountries.Cuba,
                                                               WorldCountries.Dominica,
                                                               WorldCountries.DominicanRepublic,
                                                               WorldCountries.ElSavador,
                                                               WorldCountries.Grenada,
                                                               WorldCountries.Guadeloupe,
                                                               WorldCountries.Guatemala,
                                                               WorldCountries.Haiti,
                                                               WorldCountries.Honduras,
                                                               WorldCountries.Jamaica,
                                                               WorldCountries.Martinique,
                                                               WorldCountries.Montserrat,
                                                               WorldCountries.NetherlandsAntilles,
                                                               WorldCountries.Nicaragua,
                                                               WorldCountries.Panama,
                                                               WorldCountries.PuertoRico,
                                                               WorldCountries.SaintBarthelemy,
                                                               WorldCountries.SaintKittsAndNevis,
                                                               WorldCountries.SaintLucia,
                                                               WorldCountries.SaintMartin,
                                                               WorldCountries.SaintVincentGrenadines,
                                                               WorldCountries.TrinidadTobago,
                                                               WorldCountries.TurksCaicosIslands
                                                           }
                          },
                      {
                          WorldRegions.SouthAmerica, new List<WorldCountries>()
                                                         {
                                                             WorldCountries.Argentina,
                                                             WorldCountries.Bolivia,
                                                             WorldCountries.Brazil,
                                                             WorldCountries.Chile,
                                                             WorldCountries.Colombia,
                                                             WorldCountries.Ecuador,
                                                             WorldCountries.FalklandIslands,
                                                             WorldCountries.FrenchGuiana,
                                                             WorldCountries.Guyana,
                                                             WorldCountries.Paraguay,
                                                             WorldCountries.Peru,
                                                             WorldCountries.Suriname,
                                                             WorldCountries.Uruguay,
                                                             WorldCountries.Venezuela
                                                         }
                          },
                      {
                          WorldRegions.Africa, new List<WorldCountries>()
                                                   {
                                                       WorldCountries.Angola,
                                                       WorldCountries.Benin,
                                                       WorldCountries.Botswana,
                                                       WorldCountries.BurkinaFaso,
                                                       WorldCountries.Burundi,
                                                       WorldCountries.Cameroon,
                                                       WorldCountries.CapeVerde,
                                                       WorldCountries.CentralAfricanRepublic,
                                                       WorldCountries.Chad,
                                                       WorldCountries.Comoros,
                                                       WorldCountries.CongoRepublic,
                                                       WorldCountries.CongoDemocratic,
                                                       WorldCountries.IvoryCoast,
                                                       WorldCountries.Djibouti,
                                                       WorldCountries.EquatorialGuinea,
                                                       WorldCountries.Eritrea,
                                                       WorldCountries.Ethiopia,
                                                       WorldCountries.Gabon,
                                                       WorldCountries.Gambia,
                                                       WorldCountries.Ghana,
                                                       WorldCountries.Guinea,
                                                       WorldCountries.GuineaBissau,
                                                       WorldCountries.Kenya,
                                                       WorldCountries.Lesotho,
                                                       WorldCountries.Liberia,
                                                       WorldCountries.Madagascar,
                                                       WorldCountries.Malawi,
                                                       WorldCountries.Mali,
                                                       WorldCountries.Mauritania,
                                                       WorldCountries.Mauritius,
                                                       WorldCountries.Mayotte,
                                                       WorldCountries.Mozambique,
                                                       WorldCountries.Namibia,
                                                       WorldCountries.Niger,
                                                       WorldCountries.Nigeria,
                                                       WorldCountries.Rwanda,
                                                       WorldCountries.SaintHelena,
                                                       WorldCountries.SaoTome,
                                                       WorldCountries.Senegal,
                                                       WorldCountries.Seychelles,
                                                       WorldCountries.SierraLeone,
                                                       WorldCountries.SouthAfrica,
                                                       WorldCountries.SouthGeorgiaSouthSandwichIslands,
                                                       WorldCountries.Sudan,
                                                       WorldCountries.Swaziland,
                                                       WorldCountries.Tanzania,
                                                       WorldCountries.Togo,
                                                       WorldCountries.TristanDaCunha,
                                                       WorldCountries.Uganda,
                                                       WorldCountries.Zambia,
                                                       WorldCountries.Zimbabwe
                                                   }
                          },
                      {
                          WorldRegions.Oceania, new List<WorldCountries>()
                                                    {
                                                        WorldCountries.AshmoreCartierIslands,
                                                        WorldCountries.AmericanSamoa,
                                                        WorldCountries.Australia,
                                                        WorldCountries.BritishIndianOceanTerritory,
                                                        WorldCountries.BritishSovereignBaseAreas,
                                                        WorldCountries.ChristmasIsland,
                                                        WorldCountries.CocosIslands,
                                                        WorldCountries.CookIslands,
                                                        WorldCountries.CoralSeaIslands,
                                                        WorldCountries.EastTimor,
                                                        WorldCountries.Fiji,
                                                        WorldCountries.FrenchPolynesia,
                                                        WorldCountries.Guam,
                                                        WorldCountries.Kiribati,
                                                        WorldCountries.MarshallIslands,
                                                        WorldCountries.Micronesia,
                                                        WorldCountries.Nauru,
                                                        WorldCountries.NewCaledonia,
                                                        WorldCountries.NewZealand,
                                                        WorldCountries.Niue,
                                                        WorldCountries.NorfolkIsland,
                                                        WorldCountries.NorthernMarianaIslands,
                                                        WorldCountries.Palau,
                                                        WorldCountries.PitcairnIslands,
                                                        WorldCountries.PNG,
                                                        WorldCountries.Samoa,
                                                        WorldCountries.SolomonIslands,
                                                        WorldCountries.Tokelau,
                                                        WorldCountries.Tonga,
                                                        WorldCountries.Tuvalu,
                                                        WorldCountries.Vanuatu,
                                                        WorldCountries.WallisFutuna
                                                    }
                          },
                      {WorldRegions.Antartica, new List<WorldCountries>()
                                                   {
                                                       WorldCountries.Antarctica,
                                                       WorldCountries.AustralianAntartic,
                                                       WorldCountries.BouvetIsland,
                                                       WorldCountries.BritishAntartic,
                                                       WorldCountries.FrenchSouthernAntarcticLands,
                                                       WorldCountries.HeardMcDonaldIslands,
                                                       WorldCountries.QueenMaudLand,
                                                       WorldCountries.RossDependency,
                                                   }}
                  };
    }
    */
}